# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: omw_dev
  username: root
  password: mysql
  host: localhost
  #socket: /tmp/mysql.sock
  socket: /Applications/AMPPS/var/mysql.sock

test:
  adapter: mysql2
  database: omw_test
  username: root
  password: mysql
  host: localhost
  #socket: /tmp/mysql.sock
  socket: /Applications/AMPPS/var/mysql.sock