# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69da70d991ee44e01b65fa6bd8d98b29aca1eaad71f8af77068dfa8f3da491f5ae095831cfef9d65ad87cae496e9dbc78baff5b53ba872b63739099c393abc5e

test:
  secret_key_base: c28db50eb67ed7f83d51a272dc0ef1c5009a4e46f77b4aacedb76e81d94d5ce5e5045ed5408d1ac595241d4f0a068ff6347c1b5b8a0c34c3af2480d00d0995b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
